### PR TITLE
XIVY-13261 Add no element selected property

### PR DESCRIPTION
**Pull request by ivy-edp**
I have added a default property if no element is selected, analogue to the variable editor.
grafik

### CODE REVIEW

**Review by ivy-lli — APPROVED** [review]
cool 👍 
maybe add this to the ui-components? :)

**Comment by ivy-edp** [comment]
Yes, I can do that. Should I just add the EmptyDetails component as a new section in the editor?

**Comment by ivy-lli** [comment]
yes to the sidebar

**Comment by ivy-edp** [comment]
Implemented the EmptyDetail from UI-Components in this PR: https://github.com/axonivy/form-editor-client/pull/76

**Pull request closed without merging**
